"""profile_timezone_nullable

Revision ID: fffd8023f995
Revises: 0001
Create Date: 2026-03-21 20:04:28.727448

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fffd8023f995"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'UTC'::character varying"),
    )
    op.drop_constraint(op.f("user_email_key"), "user", type_="unique")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_unique_constraint(op.f("user_email_key"), "user", ["email"], postgresql_nulls_not_distinct=False)
    op.alter_column(
        "profile",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'UTC'::character varying"),
    )
    # ### end Alembic commands ###
